### ISSUE TITLE
while running gulp command it shows error

### ISSUE THREAD

**Issue by GD-Dutta** [mendix/generator-mendix#37]
I'm using **Mendix 8.6** version and **node js 12x LTS** and while running the command gulp in the terminal it shows error
`PS C:\Users\Gayatree\test-widget\EnterToAction> gulp
[11:59:53] Using gulpfile ~\test-widget\EnterToAction\gulpfile.js
[11:59:53] Starting 'default'...
[11:59:53] Starting 'build'...
[11:59:53] Starting 'compress'...
[11:59:53] Starting 'clean'...
[11:59:53] Finished 'clean' after 16 ms
[11:59:53] Starting '<anonymous>'...
[11:59:53] Finished '<anonymous>' after 66 ms
[11:59:53] Finished 'compress' after 101 ms
[11:59:53] Finished 'build' after 120 ms
[11:59:53] Starting '<anonymous>'...
[11:59:53] '<anonymous>' errored after 3.3 ms
[11:59:53] Error: watching ./src/**/*: watch task has to be a function (optionally generated by using gulp.parallel or gulp.series)
    at Gulp.watch (C:\Users\Gayatree\test-widget\EnterToAction\node_modules\gulp\index.js:31:11)
    at C:\Users\Gayatree\test-widget\EnterToAction\gulpfile.js:47:14
    at bound (domain.js:419:14)
    at runBound (domain.js:432:12)
    at asyncRunner (C:\Users\Gayatree\test-widget\EnterToAction\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:76:11)
[11:59:53] 'default' errored after 137 ms`

@JelteMX 
 I need help sir.

**Comment by JelteMX** [comment]
I think this has to do with the gulp version, but I'm not sure. I might have some time to have a look next week
