### ISSUE TITLE
[!] TypeError: The "path" argument must be of type string. Received an instance of RegExp

### ISSUE THREAD

**Issue by Daanruijter** [mendix/generator-mendix#45]
Hi Jelte, 
I'm learning Mendix and I'm following the Mendix learning path 'Build a Pluggable Widget'. For some reason the widget is not getting built correctly by MX Generator. I tried reinstalling Node.js, Yeoman and the MX Generator, closed my Studio Pro to see whether that was it, looked for the error on Google but couldn't find it. 

Do you know what might be the problem here?

Stack trace:
Running MX Widgets Tools script lint:fix...
src\components\HelloWorldSample.tsx 276ms
src\TestWidget.editorPreview.tsx 18ms
src\TestWidget.tsx 14ms

> testwidget@1.0.0 build C:\Users\Gebruiker\documents\mendix\Build_a_pluggable_widget-main\CustomWidgets\testWidget
> pluggable-widgets-tools build:web

Running MX Widgets Tools script build:web...
Project Path: C:\Users\Gebruiker\Documents\Mendix\Build_a_pluggable_widget-main/
[!] TypeError: The "path" argument must be of type string. Received an instance of RegExp
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of RegExp
    at validateString (internal/validators.js:124:11)
    at Object.resolve (path.js:162:9)
    at C:\Users\Gebruiker\Documents\Mendix\Build_a_pluggable_widget-main\CustomWidgets\testWidget\node_modules\rollup-plugin-sass\node_modules\rollup-pluginutils\dist\pluginutils.cjs.js:183:68
    at Array.map (<anonymous>)
    at Object.createFilter (C:\Users\Gebruiker\Documents\Mendix\Build_a_pluggable_widget-main\CustomWidgets\testWidget\node_modules\rollup-plugin-sass\node_modules\rollup-pluginutils\dist\pluginutils.cjs.js:183:35)
    at Object.plugin [as default] (C:\Users\Gebruiker\Documents\Mendix\Build_a_pluggable_widget-main\CustomWidgets\testWidget\node_modules\rollup-plugin-sass\src\index.ts:134:14)
    at C:\Users\Gebruiker\Documents\Mendix\Build_a_pluggable_widget-main\CustomWidgets\testWidget\node_modules\@mendix\pluggable-widgets-tools\configs\rollup.config.js:298:45
    at Array.forEach (<anonymous>)
    at rollup_config (C:\Users\Gebruiker\Documents\Mendix\Build_a_pluggable_widget-main\CustomWidgets\testWidget\node_modules\@mendix\pluggable-widgets-tools\configs\rollup.config.js:286:23)
    at getConfigList (C:\Users\Gebruiker\Documents\Mendix\Build_a_pluggable_widget-main\CustomWidgets\testWidget\node_modules\rollup\dist\shared\loadConfigFile.js:565:11)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testwidget@1.0.0 build: `pluggable-widgets-tools build:web`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the testwidget@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gebruiker\AppData\Roaming\npm-cache\_logs\2021-08-24T10_15_58_070Z-debug.log

 Widget successfully built!! Please open Mendix Studio Pro and start playing with your new widget.

**Comment by Daanruijter** [comment]
I managed to solve the issue. I did not use the right folders for my commands:

**Being in the main folder from the Windows Powershell I need to run:**
C:\Users\Gebruiker\Documents\Mendix\Build_a_pluggable_widget-main> yo @mendix/widget x 
(in which x will be the name of the folder with all dependencies of the generated widget)

**And then in the questions from the MX Generator the project path also needs to be the main folder:**
Mendix project path: C:\Users\Gebruiker\Documents\Mendix\Build_a_pluggable_widget-main

With this configuration I was able to get custom widgets in the Widget folder.
